FUSETOOLS2-1882 - Use before/after from extester to capture screenshots
camel-tooling/camel-dap-client-vscode pull request #257
Opened 2022-12-06 12:34 UTC by mlorinc

VS Code extension tester does not support capturing screenshots in Mocha hooks by default. This change should fix it.

Signed-off-by: Marian Lorinc <mlorinc@redhat.com>

2022-12-20 14:50 UTC, djelinek commented
@mlorinc vscode-extension-tester v5.2.1 with mentioned fix was already released. You can update extester dependency and rebase.

2022-12-22 09:08 UTC, apupier requested changes
requires rebase to have a green build

2023-01-12 15:33 UTC, djelinek approved these changes

2023-01-13 16:00 UTC, apupier approved these changes

2023-01-16 10:29 UTC, merged