Add minor updates in ui-tests
camel-tooling/camel-dap-client-vscode pull request #411
Opened 2023-06-07 07:46 UTC by unsortedhashsets

- Camel Debugger tests -> increase the timeout by 1 minute (based on timeout issues during tests on macOS)
- Jbang commands with automatic reload' ->  increase the timeout by 1 minute  (based on timeout issues during tests on macOS)
- Add timeout for `driver.wait` in function `waitUntilTerminalHasText` (as discussed with @mlorinc here -> https://github.com/camel-tooling/camel-dap-client-vscode/pull/407)
- Add timeout for `driver.wait` with `replaceTextInCodeEditor` (same reason^)
- Delete after/before all/each description -> tests are failed to make screenshot with after/before all/each descriptions. example: [gh_action](https://github.com/camel-tooling/camel-dap-client-vscode/actions/runs/5197356242/jobs/9372997610) , error: `Error: Artifact path is not valid: /Camel file editor test.Camel Actions.'after all' hook: After cleanup for 'Can execute 'Run Camel Application with JBang and Debug' action'.png. Contains the following character:  Colon :`
- Change extester on vscode-uitests-tooling in imports (init. extester package uninstall)
- Delete not needed `as View...`

Hope it will stabilize tests a bit more 

Flay issues:

1) Reload -> Solved
~~Flaky issue exists on MacOS -> `await editor.selectText(text)`~~
~~`Error: NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-menu"}`~~
~~Should be fixed with new release of extester (vscode-uitests-tooling)~~

2) Debugger -> Flaky but maybe because of the extension, sometimes debugger seems is not attached  correctly (https://github.com/camel-tooling/camel-dap-client-vscode/actions/runs/5211701261/jobs/9404322203)

![Camel Debugger tests Update of a value with Camel debugger](https://github.com/camel-tooling/camel-dap-client-vscode/assets/46084942/ebbb9216-c5d1-4c84-b487-ad02cf39cac5)

```
  1) Camel Debugger tests
       Update of a value with Camel debugger:
     TimeoutError: Wait timed out after 240076ms
      at /Users/runner/work/camel-dap-client-vscode/camel-dap-client-vscode/node_modules/selenium-webdriver/lib/webdriver.js:929:17
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

3) Install test -> Sometimes happens (https://github.com/camel-tooling/camel-dap-client-vscode/actions/runs/5211701261/jobs/9404620692)

![Install test Marketplace presentation Has correct title](https://github.com/camel-tooling/camel-dap-client-vscode/assets/46084942/711d62bc-c4b0-40e7-9974-450f3b02ea24)

```
  1) Install test
       Marketplace presentation
         Has correct title:
     StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=102.0.5005.196)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
```

2023-06-07 14:26 UTC, mlorinc requested changes

2023-06-07 15:38 UTC, unsortedhashsets commented on src/ui-test/utils.ts
>              await driver.wait(until.elementIsNotVisible(debugBar));
Done, thanks!

2023-06-07 18:20 UTC, djelinek requested changes

2023-06-08 13:18 UTC, unsortedhashsets commented on src/ui-test/tests/context.menu.test.ts
> +} from 'vscode-uitests-tooling';
Done

2023-06-08 14:10 UTC, unsortedhashsets commented
@djelinek @mlorinc 
Hi, guys, please look at the description of the current flaky tests in the description of the PR
Seems the `debugger` is flaky due to the extension issue, I was able once to reproduce it locally, but it is more unstable on macos/windows

2023-06-09 08:59 UTC, djelinek commented
@unsortedhashsets nice investigation! thx

ad 2) and 3) feel free to open issues in JIRA for that and we can investigate and stabilize later in next iteration in case that is not happening very often

2023-06-09 08:59 UTC, djelinek commented
@unsortedhashsets rebase required

2023-06-09 10:54 UTC, djelinek commented
@unsortedhashsets could you please open new bug on extester project for this `Delete after/before all/each description -> tests are failed to make screenshot with after/before all/each descriptions. `.. it should work in my opinion

2023-06-09 10:56 UTC, djelinek approved these changes

2023-06-09 12:24 UTC, mlorinc approved these changes

2023-06-09 12:24 UTC, merged