FUSETOOLS2-1746: Provide UI test for Camel Debugger launch configurat…
camel-tooling/camel-dap-client-vscode pull request #544
Opened 2023-11-21 10:42 UTC by pospisilf

…ion snippet using JBang

2023-11-22 12:28 UTC, pospisilf commented
blocked by https://issues.redhat.com/browse/FUSETOOLS2-2264

2023-11-22 13:04 UTC, djelinek requested changes

2023-11-28 12:08 UTC, djelinek commented on src/ui-test/tests/command.palette.test.ts
> +    CAMEL_ROUTE_YAML_WITH_SPACE
weird spaces at the end of this line

2023-11-28 12:11 UTC, djelinek commented on src/ui-test/utils.ts
> + * Removes folder using fs.
need to modify a description after change of this method to more generic

2023-11-28 16:30 UTC, djelinek commented on src/ui-test/utils.ts
> + * @param folder Path of resource to remove.
only `folder` path?

2023-11-28 17:37 UTC, merged