FUSETOOLS2-2313: Display variable values with Exchange scope during d…
camel-tooling/camel-dap-client-vscode pull request #620
Opened 2024-04-10 22:27 UTC by pospisilf

…ebugging

2024-04-11 08:45 UTC, apupier requested changes
I think it is worthy mentioning in the commit message that it is the tests which are added by this commit

2024-04-11 08:45 UTC, apupier commented on src/ui-test/resources/variablesTest.java
> +public class variablesTest extends RouteBuilder {
```suggestion
public class VariablesTest extends RouteBuilder {
```

2024-04-11 08:45 UTC, apupier commented on src/ui-test/resources/variablesTest.java
filename to change to foollow Java convention: VariablesTest.java

2024-04-16 17:01 UTC, djelinek commented
@pospisilf the new tests are failing due to last changes on PR

2024-04-16 19:57 UTC, pospisilf commented
> @pospisilf the new tests are failing due to last changes on PR

Fixed. Thanks for noticing.

2024-04-17 13:42 UTC, djelinek approved these changes

2024-04-18 11:06 UTC, djelinek commented
> I think it is worthy mentioning in the commit message that it is the tests which are added by this commit

@apupier which commit do you mean?

2024-04-18 11:25 UTC, pospisilf commented
> > I think it is worthy mentioning in the commit message that it is the tests which are added by this commit
> 
> @apupier which commit do you mean?

already solved in past by me, sorry

2024-04-18 13:27 UTC, apupier approved these changes

2024-04-18 13:28 UTC, merged