FUSETOOLS-2362: Adds UI tests for extra parameters when lauching with JBang
camel-tooling/camel-dap-client-vscode pull request #634
Opened 2024-05-06 13:10 UTC by hdamarcelo

Adds tests specific to manipulating array settings which is the type for
the "extra launch parameter" setting.

Signed-off-by: Marcelo Henrique Diniz de Araujo <mdinizde@redhat.com>

2024-05-06 13:14 UTC, apupier commented on src/ui-test/tests/camel.settings.test.ts
> +    describe.only('Update Extra Launch Parameter setting', function () {
do not forget to remove the .only

2024-05-06 13:26 UTC, apupier requested changes
The added tests are mostly verifying that the VS Code UI of preferences is workign and that we declare the type to array of string in the package.json.
To be more effective, the test should add one or two parameter, then start a camel route and check that the added parameters are used correctly by checking the terminal that has some specific text

2024-05-07 08:39 UTC, apupier approved these changes

2024-05-07 09:28 UTC, djelinek approved these changes

2024-05-07 13:37 UTC, merged