FUSETOOLS2-2408: UI tests for Support pause of Camel debugger
camel-tooling/camel-dap-client-vscode pull request #706
Opened 2024-08-06 11:21 UTC by pospisilf

2024-08-13 00:19 UTC, apupier requested changes

2024-08-13 00:19 UTC, apupier commented on src/ui-test/tests/pause.test.ts
> +describe.only("Support pause of Camel debugger", function () {
remove .only

2024-08-13 09:52 UTC, djelinek reviewed
it seems there are cases where it can fail, could you please take a look and improve a bit dynamic waiting for the problematic elements?

```
  1) Support pause of Camel debugger
       Multiple routes pause:
     ElementNotInteractableError: element not interactable
  (Session info: chrome=118.0.5993.159)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:521:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:514:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:446:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:742:17)
      at async DebugCallStackSection.getContainer (node_modules/@redhat-developer/page-objects/out/components/sidebar/tree/custom/CustomTreeSection.js:68:9)
      at async DebugCallStackSection.getVisibleItems (node_modules/@redhat-developer/page-objects/out/components/sidebar/tree/custom/CustomTreeSection.js:42:27)
      at async Context.<anonymous> (out/ui-test/tests/pause.test.js:74:23)
```

2024-08-14 10:20 UTC, apupier approved these changes

2024-08-19 20:04 UTC, pospisilf commented
> it seems there are cases where it can fail, could you please take a look and improve a bit dynamic waiting for the problematic elements?
> 
> ```
>   1) Support pause of Camel debugger
>        Multiple routes pause:
>      ElementNotInteractableError: element not interactable
>   (Session info: chrome=118.0.5993.159)
>       at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:521:15)
>       at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:514:13)
>       at Executor.execute (node_modules/selenium-webdriver/lib/http.js:446:28)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:742:17)
>       at async DebugCallStackSection.getContainer (node_modules/@redhat-developer/page-objects/out/components/sidebar/tree/custom/CustomTreeSection.js:68:9)
>       at async DebugCallStackSection.getVisibleItems (node_modules/@redhat-developer/page-objects/out/components/sidebar/tree/custom/CustomTreeSection.js:42:27)
>       at async Context.<anonymous> (out/ui-test/tests/pause.test.js:74:23)
> ```

Yes but this case is random happens only on Mac OS with 1.86.2 VS Code. There should be no issue with 1.90.2 which we are planning to test soon si I think this PR can wait until 1.90.2 will be used.

2024-08-21 00:14 UTC, djelinek approved these changes

2024-09-03 11:34 UTC, merged