feat: upgrade ESLint to version 9
camel-tooling/camel-dap-client-vscode pull request #748
Opened 2024-10-18 07:05 UTC by pospisilf

2024-10-18 11:47 UTC, apupier approved these changes

2024-10-21 08:29 UTC, apupier requested changes
the CycloneDX version must be updated in JenkinsFile too

2024-10-22 12:57 UTC, pospisilf commented
> the CycloneDX version must be updated in JenkinsFile too

Updated, thanks.

2024-10-24 08:42 UTC, apupier approved these changes

2024-10-24 08:44 UTC, djelinek approved these changes

2024-10-24 08:45 UTC, merged